insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '6767929598305126', '75290', 'Loeprich', '6:30 PM', 'L', '711-843-2550', 'vsebastian0@craigslist.org');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Franny', 'Goodlife', '40953877A', '0J2Y8OdY', 'fgoodlife0@wikispaces.com', true, 1);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '6761626824610641373', '6', '1st', '4:07 PM', 'F', '620-111-7569', 'arigden1@ox.ac.uk');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Lu', 'Helbeck', '91628755R', 'lPj5xBaK', 'lhelbeck1@webeden.co.uk', false, 3);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '0604769022337410140', '92', 'Buhler', '8:29 PM', 'S', '651-762-9150', 'mswindles2@soundcloud.com');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Edwina', 'Kemmet', '03649018D', 'x3y4aA04', 'ekemmet2@zdnet.com', false, 5);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '3574574796303984', '5', 'Meadow Valley', '8:22 AM', 'Z', '485-241-4402', 'tknobell3@prnewswire.com');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Eduard', 'Denney', '03986580W', 'e1a3h4fT', 'edenney3@angelfire.com', false, 7);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '30102141794535', '75560', 'Pierstorff', '11:51 PM', 'F', '585-165-8435', 'cweathey4@altervista.org');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Ludovika', 'Bachelor', '46585307J', '6O21uJfD', 'lbachelor4@pen.io', false, 9);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '30497860510199', '602', 'Arapahoe', '6:13 PM', 'K', '985-311-6616', 'amaccallam5@privacy.gov.au');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Suellen', 'Schapiro', '62923098G', '49hB2VuW', 'sschapiro5@blogtalkradio.com', false, 11);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '3547074621755064', '812', 'Birchwood', '1:11 AM', 'S', '587-468-3592', 'mcorstan6@dailymail.co.uk');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Ode', 'Crichmer', '28254864F', 'vB5Rv81Q', 'ocrichmer6@mit.edu', true, 13);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '337941834482274', '53', 'School', '8:03 PM', 'G', '259-850-4387', 'zcornier7@geocities.jp');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Lowe', 'Splain', '94542031A', 'rHhYkXx9', 'lsplain7@studiopress.com', false, 15);

insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Cobalt', 'Island Oasis - Strawberry', '52.6', false, '2.0', '618', false, 'qjaummzlat', 'Chevrolet');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'XC70', 'Beef - Kobe Striploin', '55.4', true, '5.7', '993', false, 'ybbtdgyguo', 'Volvo');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'GranSport', 'Ice Cream Bar - Drumstick', '44.0', false, '1.7', '674', true, 'uoyyuwpuev', 'Maserati');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Ram 3500', 'Broom - Angled', '31.7', true, '0.8', '444', false, 'spgxxbysht', 'Dodge');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Pathfinder', 'Tart - Raisin And Pecan', '23.1', false, '5.4', '974', true, 'updmdixldu', 'Nissan');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'SLK-Class', 'Water - Evian 355 Ml', '22.3', false, '0.5', '615', true, 'uscsloosnv', 'Mercedes-Benz');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), '4Runner', 'Plasticforkblack', '35.7', true, '4.0', '460', true, 'eubayxmpal', 'Toyota');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Mustang', 'Fruit Mix - Light', '57.8', true, '4.1', '236', false, 'edzzbnzhny', 'Ford');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Mighty Max Macro', 'Maple Syrup', '88.7', false, '7.1', '365', false, 'riizfpnzsu', 'Mitsubishi');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Fit', 'Bread Crumbs - Japanese Style', '70.1', true, '0.5', '404', true, 'ydjicwsmez', 'Honda');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), '960', 'Ostrich - Prime Cut', '07.6', false, '7.9', '840', true, 'dkhwjnvlen', 'Volvo');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'STS-V', 'Sprouts - Bean', '25.4', true, '6.8', '139', true, 'corfktfvjd', 'Cadillac');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'RS 4', 'Bay Leaf Ground', '76.7', true, '8.4', '777', true, 'abcegalegr', 'Audi');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Avalanche 1500', 'Mayonnaise - Individual Pkg', '37.7', false, '1.9', '872', true, 'mfzehaejbc', 'Chevrolet');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Suburban 1500', 'Tomatoes - Grape', '29.0', true, '7.7', '568', true, 'sjbmzmxxpa', 'Chevrolet');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Mountaineer', 'Onions - Spanish', '98.2', false, '0.8', '626', true, 'lhjuwuvfoz', 'Mercury');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Daewoo Magnus', 'Mix - Cocktail Ice Cream', '72.3', false, '0.0', '267', false, 'aumlmenfee', 'Suzuki');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'E-Class', 'Lychee - Canned', '60.5', true, '9.1', '183', true, 'stxspvlaiq', 'Mercedes-Benz');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'SLX', 'Paste - Black Olive', '88.2', false, '5.4', '567', true, 'gixjlbwyne', 'Acura');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Mazda3', 'Pasta - Angel Hair', '27.0', false, '3.7', '183', false, 'jzottiqpos', 'Mazda');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Diablo', 'Rolled Oats', '92.1', true, '1.2', '328', true, 'xyobxbyfbh', 'Lamborghini');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Sephia', 'Rappini - Andy Boy', '04.7', true, '7.2', '158', true, 'sbwubmtctg', 'Kia');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Premier', 'Beef Flat Iron Steak', '03.3', false, '6.6', '234', false, 'xmxdoffszx', 'Eagle');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Rio', 'Tea Leaves - Oolong', '60.9', false, '8.2', '957', true, 'ezuckljnfw', 'Kia');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Jetta', 'Flour - Cake', '65.3', false, '7.5', '044', true, 'uuipffpfma', 'Volkswagen');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Sunfire', 'Doilies - 8, Paper', '53.0', false, '8.6', '018', false, 'kzghchoiar', 'Pontiac');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Ram Van 2500', 'Squash - Butternut', '89.8', true, '4.5', '880', true, 'czhpxrfrwa', 'Dodge');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), '98', 'Apple - Granny Smith', '30.0', false, '8.4', '755', false, 'stueonznss', 'Oldsmobile');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), '90', 'Oil - Margarine', '86.1', false, '3.0', '849', true, 'hazxodbycb', 'Audi');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Suburban 1500', 'Sauce - Plum', '61.9', true, '9.1', '489', true, 'vgizburhol', 'Chevrolet');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'D250 Club', 'Sage Derby', '69.6', true, '2.1', '417', true, 'bgnsnrpvca', 'Dodge');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Rodeo', 'Juice - V8, Tomato', '99.8', true, '8.9', '505', true, 'etodoyaico', 'Isuzu');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Odyssey', 'Beans - Kidney, Canned', '54.5', false, '8.2', '293', true, 'slvaqcrlep', 'Honda');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'XLR', 'Bread - Onion Focaccia', '34.3', false, '9.6', '131', true, 'alrwmblbbo', 'Cadillac');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Eclipse', 'Lamb - Pieces, Diced', '10.6', true, '8.4', '897', true, 'pizigzdcwd', 'Mitsubishi');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Avalanche', 'Mushroom - Chantrelle, Fresh', '44.1', false, '8.7', '712', true, 'memjbaoble', 'Chevrolet');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'IS F', 'Egg Patty Fried', '74.2', true, '0.6', '671', true, 'zmqpivfebx', 'Lexus');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Avalon', 'Crab - Soft Shell', '43.7', true, '1.6', '893', false, 'ciuqgrxbto', 'Toyota');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'CL', 'Vodka - Lemon, Absolut', '17.4', false, '2.7', '744', true, 'ufprzqghgg', 'Acura');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'C-Class', 'Wine - White, Concha Y Toro', '37.1', false, '7.3', '582', true, 'hvufoobocq', 'Mercedes-Benz');

insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('39', '00', 'in', 'zar6', 21);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('71', '90', 'vk', 'rkk3', 22);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('20', '53', 'th', 'nzi4', 23);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('13', '23', 'fd', 'nug2', 24);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('53', '78', 'iq', 'odf3', 25);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('00', '68', 'vb', 'lys5', 26);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('67', '25', 'sc', 'xwq0', 27);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('10', '72', 'nc', 'rbr7', 28);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('31', '85', 'mu', 'shc5', 29);
insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('10', '76', 'mz', 'xov3', 30);


insert into accesorios (tipo, capacidad, id) values ('CR-V', '1922', 31);
insert into accesorios (tipo, capacidad, id) values ('Diamante', '8770', 32);
insert into accesorios (tipo, capacidad, id) values ('Avalanche', '0917', 33);
insert into accesorios (tipo, capacidad, id) values ('F150', '5996', 34);
insert into accesorios (tipo, capacidad, id) values ('Quattroporte', '8526', 35);
insert into accesorios (tipo, capacidad, id) values ('Prowler', '7208', 36);
insert into accesorios (tipo, capacidad, id) values ('Edge', '4984', 37);
insert into accesorios (tipo, capacidad, id) values ('350Z', '1875', 38);
insert into accesorios (tipo, capacidad, id) values ('Safari', '3149', 39);
insert into accesorios (tipo, capacidad, id) values ('Rally Wagon G3500', '3841', 40);

insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Carry', '52', '5976', 'Steel Wool', 'Horror|Thriller', '14cmx15cmx13cm', 41);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Waverly', '65', '0808', 'Pork - Butt, Boneless', 'Children|Comedy|Fantasy|Romance', '14cmx58cmx61cm', 42);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Richmound', '82', '5362', 'Island Oasis - Cappucino Mix', 'Adventure', '51cmx73cmx99cm', 43);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Liv', '21', '1615', 'Scallops - 10/20', 'Animation|Children', '57cmx84cmx40cm', 44);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Boote', '60', '8238', 'Horseradish - Prepared', 'Comedy|Crime|Drama', '86cmx38cmx65cm', 45);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Carly', '91', '1959', 'Cheese - Asiago', 'Crime|Documentary', '38cmx07cmx61cm', 46);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Florella', '90', '3828', 'Beer - Moosehead', 'Action|Drama', '39cmx98cmx03cm', 47);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Florance', '50', '4334', 'Goat - Whole Cut', 'Comedy', '19cmx86cmx25cm', 48);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Rog', '19', '7141', 'Pastry - Banana Tea Loaf', 'Drama|Thriller', '35cmx12cmx09cm', 19);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Minny', '06', '4226', 'Wine - Red, Gamay Noir', 'Action|Crime|Thriller', '56cmx50cmx86cm', 20);

