insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '6767929598305126', '75290', 'Loeprich', '6:30 PM', 'L', '711-843-2550', 'vsebastian0@craigslist.org');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Franny', 'Goodlife', '40953877A', '1234', 'fgoodlife0@wikispaces.com', true, 1);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '6761626824610641373', '6', '1st', '4:07 PM', 'F', '620-111-7569', 'arigden1@ox.ac.uk');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Lu', 'Helbeck', '91628755R', '1234', 'lhelbeck1@webeden.co.uk', false, 3);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '0604769022337410140', '92', 'Buhler', '8:29 PM', 'S', '651-762-9150', 'mswindles2@soundcloud.com');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Edwina', 'Kemmet', '03649018D', '1234', 'ekemmet2@zdnet.com', false, 5);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '3574574796303984', '5', 'Meadow Valley', '8:22 AM', 'Z', '485-241-4402', 'tknobell3@prnewswire.com');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Eduard', 'Denney', '03986580W', '1234', 'edenney3@angelfire.com', false, 7);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '30102141794535', '75560', 'Pierstorff', '11:51 PM', 'F', '585-165-8435', 'cweathey4@altervista.org');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Ludovika', 'Bachelor', '46585307J', '1234', 'lbachelor4@pen.io', false, 9);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '30497860510199', '602', 'Arapahoe', '6:13 PM', 'K', '985-311-6616', 'amaccallam5@privacy.gov.au');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Suellen', 'Schapiro', '62923098G', '49hB2VuW', 'sschapiro5@blogtalkradio.com', false, 11);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '3547074621755064', '812', 'Birchwood', '1:11 AM', 'S', '587-468-3592', 'mcorstan6@dailymail.co.uk');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Ode', 'Crichmer', '28254864F', '1234', 'ocrichmer6@mit.edu', true, 13);
insert into Datos_De_Compra (id, tarjeta_De_Credito, codigo_Postal, direccion, hora_Entrega, comentarios_Extra, telefono_Contacto, email_Contacto) values (NEXTVAL('hibernate_sequence'), '337941834482274', '53', 'School', '8:03 PM', 'G', '259-850-4387', 'zcornier7@geocities.jp');
insert into usuario (id, nombre, apellidos, dni, password, email, admin, Datos_De_Compra_Id) values (NEXTVAL('hibernate_sequence'), 'Lowe', 'Splain', '94542031A', '1234', 'lsplain7@studiopress.com', false, 15);

insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Kingston DataTraveler 32GB', 'USB 3.0 de próxima generación', '6.5', false, '6.5', '618', true, 'kingstonDatatraveler.jpg', 'Kingston');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'ASUS DUAL-GTX1060-O6G', 'La potente targeta 1060 de ASUS', '305.70', true, '270', '30', true, 'AsusGtx1060.jpg', 'ASUS');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Alfombrilla MARS', 'Alfombrilla gaming de tamaño pequeño', '15', false, '15', '412', true, 'AlfombrillaMars.jpg', 'Mars');
insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'AzerothPC Gold', 'Nuestro producto esrella', '1299.99', true, '1116', '100', true, 'AzerothPCGold.jpg', 'AzerothPcs');

insert into componentes (memoria, velocidad, socket, tipo_Memoria, id) values ('6GB', '1708 MHz', 'ninguno', 'GDDR5', 18);
insert into accesorios (tipo, capacidad, id) values ('Alfombrilla', '0.0', 19);
insert into ordenador (procesador, ram, disco_Duro, sistema_Operativo, tipo, dimensiones, id) values ('Intel Core i5-9600K 3.7Ghz', '16', 'HDD 2TB SATA3 SSD 240GB SATA3', 'Windows 10', 'SobreMesa', '405x455x210mm (An x Al x Pr)', 20);

insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Logitech G430 Gaming', 'Auriculares gaming Logitech', '69.99', false, '69.99', '45', true, 'logitechg430.jpg', 'Logitech');
insert into accesorios (tipo, capacidad, id) values ('Auriculares', '0.0', 20);

insert into producto (id, nombre, descripcion, precio, en_Oferta, precio_Con_Descuento, cantidad, disponible, imagen, marca) values (NEXTVAL('hibernate_sequence'), 'Tacens Mars MM218', 'Raton óptico con 10000dpi', '69.99', false, '18', '780', true, 'tacensMars.jpg', 'Mars');
insert into accesorios (tipo, capacidad, id) values ('Raton', '0.0', 21);